// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Capture(): $CancellablePromise<[$models.OWHero[], $models.OverwatchFilters]> {
    return $Call.ByID(3605231503).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType2($result[1]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $models.OWHero.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.OverwatchFilters.createFrom;
