// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OWHero {
    "Name": string;
    "Color": string;
    "Image": string;
    "PickRate": number;
    "WinRate": number;

    /** Creates a new OWHero instance. */
    constructor($$source: Partial<OWHero> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Color" in $$source)) {
            this["Color"] = "";
        }
        if (!("Image" in $$source)) {
            this["Image"] = "";
        }
        if (!("PickRate" in $$source)) {
            this["PickRate"] = 0;
        }
        if (!("WinRate" in $$source)) {
            this["WinRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OWHero instance from a string or object.
     */
    static createFrom($$source: any = {}): OWHero {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OWHero($$parsedSource as Partial<OWHero>);
    }
}

export class OverwatchFilters {
    "role": string;
    "input": string;
    "gameMode": string;
    "rankTier": string;
    "map": string;
    "region": string;

    /** Creates a new OverwatchFilters instance. */
    constructor($$source: Partial<OverwatchFilters> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("gameMode" in $$source)) {
            this["gameMode"] = "";
        }
        if (!("rankTier" in $$source)) {
            this["rankTier"] = "";
        }
        if (!("map" in $$source)) {
            this["map"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverwatchFilters instance from a string or object.
     */
    static createFrom($$source: any = {}): OverwatchFilters {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OverwatchFilters($$parsedSource as Partial<OverwatchFilters>);
    }
}
